<script src="<?= base_url() ?>assets/js/system/cotizacion/cotizacion_mantenimiento.js"></script>
<script src="<?= base_url() ?>assets/js/system/tservicio/tservicio.js"></script>
<script src="<?= base_url() ?>assets/js/system/clasificacion/clasificacion.js"></script>
<script src="<?= base_url() ?>assets/js/system/actividad/actividad.js"></script>
<script src="<?= base_url() ?>assets/js/system/grupo/grupo.js"></script>
<script src="<?= base_url() ?>assets/js/system/involucrado/involucrado_juridico.js"></script>
<script src="<?= base_url() ?>assets/js/system/involucrado/involucrado_natural.js"></script>
<script src="<?= base_url() ?>assets/js/system/contacto/contacto.js"></script>
<script src="<?= base_url() ?>assets/js/system/servicio/servicio.js"></script>