<script src="<?= base_url() ?>assets/js/system/tasacion/tasacion_cliente.js"></script>
<script src="<?= base_url() ?>assets/js/system/tasacion/tasacion_propietario.js"></script>
<script src="<?= base_url() ?>assets/js/system/tasacion/tasacion_solicitante.js"></script>
<script src="<?= base_url() ?>assets/js/system/tasacion/tasacion_zonificacion.js"></script>
<script src="<?= base_url() ?>assets/js/system/tasacion/tasacion_clase.js"></script>
<script src="<?= base_url() ?>assets/js/system/tasacion/tasacion_marca.js"></script>
<script src="<?= base_url() ?>assets/js/system/tasacion/tasacion_modelo.js"></script>
<script src="<?= base_url() ?>assets/js/system/tasacion/tasacion_tipo_no_registrado.js"></script>
<script src="<?= base_url() ?>assets/js/system/tasacion/tasacion_mant.js"></script>